// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTMKXG9EyIalIjPZ5Gv5uswrabaYf1-Rg',
    appId: '1:601486633446:web:a22a29d74d8336f3d94e27',
    messagingSenderId: '601486633446',
    projectId: 'btechproject-6e661',
    authDomain: 'btechproject-6e661.firebaseapp.com',
    storageBucket: 'btechproject-6e661.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv5pF9_CptH58qZP7AXZHNNg7hcnoEAmI',
    appId: '1:601486633446:android:3edfc6454cfe2a0dd94e27',
    messagingSenderId: '601486633446',
    projectId: 'btechproject-6e661',
    storageBucket: 'btechproject-6e661.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUDbPenDzZhq7xg02EFEIt9t_dYih6SB4',
    appId: '1:601486633446:ios:80f29056f0533d75d94e27',
    messagingSenderId: '601486633446',
    projectId: 'btechproject-6e661',
    storageBucket: 'btechproject-6e661.firebasestorage.app',
    iosBundleId: 'com.example.btechProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUDbPenDzZhq7xg02EFEIt9t_dYih6SB4',
    appId: '1:601486633446:ios:80f29056f0533d75d94e27',
    messagingSenderId: '601486633446',
    projectId: 'btechproject-6e661',
    storageBucket: 'btechproject-6e661.firebasestorage.app',
    iosBundleId: 'com.example.btechProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTMKXG9EyIalIjPZ5Gv5uswrabaYf1-Rg',
    appId: '1:601486633446:web:8925bef75301c02fd94e27',
    messagingSenderId: '601486633446',
    projectId: 'btechproject-6e661',
    authDomain: 'btechproject-6e661.firebaseapp.com',
    storageBucket: 'btechproject-6e661.firebasestorage.app',
  );
}
